include/cocaine/rpc/asio/channel.hpp
include/cocaine/rpc/asio/readable_stream.hpp
include/cocaine/rpc/asio/writable_stream.hpp

This change allows to work with Cocaine channels in conjunction with either pure asio or boost::asio.

[API] Deduce socket type via its protocol.

---

src/service/node/slave.cpp

Under Trusty in OpenStack the timestamp was generated in nanoseconds. Also cocaine-tool crashlog list expects the timestamp to be in microseconds.

[Slave] Cast timestamp of crashlogs to microseconds explicitly.

---

src/service/node/slave.cpp

Sometimes a segfault can happen when output in slave_t (for example on spawn error) was not initialized and timer run out.

Fix for segfault on spawn failure

---

include/cocaine/detail/bootstrap/logging.hpp
src/logging.cpp

After this commit, cocaine-core can be safely linked with multiple libraries, that are compiled with Blackhole version different from the Cocaine compiled one.
For example, Elliptics uses Blackhole v0.2 (much legacy, so ancient, wow <img src="http://cdn7.staztic.com/app/a/3560/3560202/doge-snake-1-l-124x124.png" height="30" width="30">) and produces the plugin, which is dependent from Cocaine, which uses Blackhole v0.5. Bad things can happen.
Internally Blackhole's versioned namespaces are inline, so this change shouldn't change anything in the codebase. Unfortunately, only clang allows to extend inline namespaces without specifying that namespace explicitly.

[Logging] Blackhole with versioned namespaces.

---

include/cocaine/rpc/queue.hpp
include/cocaine/rpc/slot/deferred.hpp
include/cocaine/rpc/slot/streamed.hpp
include/cocaine/tuple.hpp

Deffered is quite usefull even for custom protocol transitions. This patch allows defferred and streamed to be used in custom slots.
Also some const callables such as std::mem_fn can call only underlying const methods. So in general we might want to pass reference instead of const reference to tuple::invoke. This patch only allows passing rvalue references additionally to lvalue const references to be compatible with old behaviour.

Deferred for custom slot

---

src/service/node/app.cpp

```upstream.send<protocol::chunk>``` returns moved pointer and we don't update the current upstream with this pointer, so next *write*, *close*, *error* will lead to EXC_BAD_ACCESS

[App] Don't throw moved ptr

---

include/cocaine/forwards.hpp
include/cocaine/rpc/asio/channel.hpp

Extend channel's API to be usable with custom encoder/decoder types.
Personally I need this one for native framework to avoid code duplication.

[API] Channel extension.

---

.travis.yml
include/cocaine/context.hpp
include/cocaine/signal.hpp

Use retroactive signals for service lifetime events in Context so that new subscribers to those signals are up-to-date with service lifetimes.

[Core] Retroactive signals.

---

debian/changelog
src/service/node/slave.cpp

Right now it's set to localhost:port by mistake. So an isolated worker can't resolve locator service.
Is it better to pass a comma-separated list of endpoints here like in resolving of a service?

Fix --locator arg in slave

---

include/cocaine/idl/locator.hpp
include/cocaine/rpc/dispatch.hpp
include/cocaine/rpc/graph.hpp
include/cocaine/rpc/traversal.hpp
include/cocaine/traits/graph.hpp
src/api.cpp
src/service/locator.cpp

Instead of rather meaningless 'basis' and 'point', this commit implements a new
naming scheme for graph types - root and node. Which are common names for those
things.

[RPC] Renamed graph types.

---

cocaine-bf.spec
debian/changelog
src/service/node/slave.cpp

After a slave termination there can be pending heartbeat events. In this case we shouldn't try to send a heartbeat to the already stopped worker, because its channel has been cancelled at that moment.

[Bug Fix] Do not write on already deleted channel.

---

include/cocaine/rpc/upstream.hpp

Upstream states are redundant since the upstream sealing is now handled by typed upstream transitions.

[RPC] Drop upstream states.

---

include/cocaine/api/connect.hpp
include/cocaine/detail/chamber.hpp
include/cocaine/detail/engine.hpp
include/cocaine/rpc/dispatch.hpp
include/cocaine/rpc/session.hpp
include/cocaine/rpc/upstream.hpp
include/cocaine/traits/tuple.hpp
src/actor.cpp
src/api.cpp
src/chamber.cpp
src/context.cpp
src/engine.cpp
src/service/locator.cpp
src/session.cpp

Trello: https://trello.com/c/95HRjhQa
* Sessions no longer depend on `boost::signals2`. The shutdown signal wasn't required in the first place, since under highload system will reuse fds fast enough to replace stale sessions in the engine's map, and for quiet times engines will now garbage collect stale sessions every 60 seconds.
* Sessions now log stuff. That means improvements over `uncaught_error` without any details about what error was not actually caught.
* Much more predictable dispatch discard policy. Note that `discard()` call may or may not be accompanied by `std::error_code`.

[RPC] Refactored sessions.

---

debian/libcocaine-dev.install

subj. Also now cocaine/context folder installed correctly.

Install all headers as only proper headers are installed by cmake.

---

include/cocaine/api/gateway.hpp
include/cocaine/detail/gateway/adhoc.hpp
include/cocaine/detail/service/locator.hpp
include/cocaine/tuple.hpp
src/gateway/adhoc.cpp
src/service/locator.cpp

When there are more than one service version in the cluster, properly partition service metadata by version and resolve only the latest version. We'll add an ability to request specific versions later.

[Bugfix] Multiple service versions in the cluster.

---

cocaine-bf.spec
debian/changelog
src/service/node.cpp
src/service/node/app.cpp
src/service/node/engine.cpp

When Cocaine was unable to start an app it threw an exception, which wasn't been caught. It led to app/service list inconsistency.
For example:
```
> node.list
> []
>
> node.start_app :http, :default
> [1, "fuck you"]
>
> node.list
> ["http"]
>
> node.pause_app :http
> [1, "app 'http' is not running"]
```
This commit should fix that behavior.

[Bug Fix] Fixed app/service list consistency.

---

include/cocaine/traits/literal.hpp
include/cocaine/traits/tuple.hpp

Given:
- T and U, where T is convertible to U.
- An event with typelist<U, Args...>.
- Arguments v: T, other: Args...
This commit fixes improper behavior when an argument of type T is packed using `type_traits<T>(v)` instead of `type_traits<U>(v)`.
Without this change the https://github.com/cocaine/cocaine-core/blob/kobolog/error-categories/include/cocaine/rpc/slot/blocking.hpp#L56 for example invokes improper behavior, packing an int instead of calling conversion constructor.

[Bug Fix] Pack typelists with implicit convertions

---

src/service/locator.cpp
src/service/locator/routing.cpp

Both of them make no sense from the routing point.

Forbid empty groups as like as groups with zero total weights.

---

include/cocaine/rpc/asio/encoder.hpp

Otherwise stuff like `upstream.send<protocol::write>(ec, "fuck you");` won't work.

Fixed string literals binding.

---

include/cocaine/forwards.hpp
include/cocaine/logging.hpp
src/context/config.cpp
src/runtime/logging.cpp

Accidentally we have broken an API, so we have to rollback
to prevent further damage.
Also the logging priorities now have strictly associated
numbers, cause they are part of public API.

Logging: no more trace.

---

include/cocaine/rpc/asio/decoder.hpp

We have to clear msgpack zone every decoding iteration to prevent memory leaking for objects structure, cause they have no way to notify about self destruction. Hope someday we migrate to v1.* and everything will be fine automatically.
It's also recommended to rebuild all your dependencies, because the changed file is a part of public API and implicitly marked as inline, which may result in unexpected behavior.

Hotfix: clear msgpack zone every decode iteration.

---

include/cocaine/platform.hpp

Fedora 22 uses gcc 5.1 and fails to build without these defines

platform: turn on all gcc 4x defines for 5x compiler

---

src/session.cpp

Otherwise it may lead to deadlock.

Technical debt: do not allow detach session more than once.

---

src/errors.cpp

Now argument count properly corresponds the pattern.
Previously:
```
[E]: unable to announce local endpoints: <unable to format message - boost::too_many_args: format-string referred to less arguments than were passed> [source: locator:cluster]
```
Becomes:
```
[E]: unable to announce local endpoints: [65] send_to: No route to host [source: locator:cluster]
```

Fix(errors): remove excess argument.

---

src/session.cpp

This change adds more information about dropped channels by displaying
channel id.
In logs it will be: `uncaught invocation exception: [4] 42: specified
channel was revoked`

Misc(session): display revoked channel id.

---

include/cocaine/detail/engine.hpp
src/engine.cpp

Just canceling timer is not enough to be sure that it's stopped.
ASIO `timer::cancel` returns number of actually cancelled completion
handlers. Depending on timeout resolution it may return 0, which means
that completion handler has already been posted into the event loop and
it cannot be cancelled. Thus, it would be fired and reschedule timer
again. This led to the infinite hanging on joining thread while the event
loop processing repeating timer events.
This commit adds timer explicit lifetime tracking before asynchronous
waiting.

Fix(engine): fixed infinite hanging on engine shutdown.

---

src/actor.cpp

- Actor endpoint now is saved for further usage (logging) before
binding.
- More verbose error logging - now it's possible to see what endpoint
failed to be bound.

Misc(actor): tiny bind preparation fixes.

---

src/service/locator/routing.cpp

Without this change there will be log(N) reallocations.

perf(continuum): preallocate enough space for dump

---

CMakeLists.txt

On newer clang there is new warning check, which is triggered by ASIO headers.

fix(cmake): hide -Wunused-local-typedef for asio

---

include/cocaine/detail/service/locator.hpp
include/cocaine/idl/locator.hpp
src/service/locator.cpp

This commit makes outgoing streams for routers auto disposable. Without
this change the streams are not collected until unsuccessful write attempt.
In our production we have about 50k dead streams which made the Locator
completely freeze attempting to notify them all.
Also this commit allows clients to unsubscribe manually without
transport destruction.
Moreover this makes the protocol more clean.
Also added more logs.

fix(locator): make router streams auto disposable

---

src/actor.cpp
src/actor_unix.cpp
src/engine.cpp

This is handy for logging postprocessors which can create separate directory depending on attribute value.
- Also use uniform initialization for logging attributes, it makes the code cleaner.
- Thread name is also touched.

style(logs): consistency for logging prefixes
